client_timeout 75;
client_header_buffer_size 2k;
server {
	listen localhost:8085;
	# root /home/vic/Documents/webserver/www;
	index index.html;
	autoindex on;
	cgi_bin .py /usr/bin/python3;
	cgi_bin .pl /usr/bin/perl;
	location / {
		autoindex on;
		index index.html;
	}
	location /test_folder {
		autoindex off;
	}
	location /cgi-bin {
		allowed_methods GET POST;
		upload_directory /home/vic/Documents/cprojects/webserver/www/uploads/;
	}
	location /cgi-bin/delete_file.py {
		allowed_methods GET DELETE;
		upload_directory /home/vic/Documents/cprojects/webserver/www/uploads/;
	}
	location /rover {
		allowed_methods GET;
		return 301 "https://cdn.sanity.io/files/4zrzovbb/website/a62d1ae88259144dd376b5920c592476a5ad45e5.mp4";
	}
}


client_max_body_size 7m;
